In [3]:
import pandas as pd 
import numpy as np

In [4]:
weather_na_df = pd.read_excel('6-weatherna.xlsx')

In [5]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [6]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [7]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [8]:
weather_na_df.dropna()

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [9]:
weather_na_df['Istanbul']

0    20.0
1    21.0
2     NaN
3    22.0
4    25.0
5    28.0
6    15.0
7    20.0
8    22.0
Name: Istanbul, dtype: float64

In [10]:
weather_na_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
weather_na_df.fillna(20)

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [15]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [16]:
weather_na_df.median()

Istanbul     21.5
New York     13.5
Amsterdam    15.5
Paris        15.0
dtype: float64

In [17]:
#Group by

In [18]:
df = pd.read_csv('6-employee.csv')

In [19]:
df

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York

In [21]:
df.isna()

    Department  Employee  Salary  Experience   City
0        False     False   False       False  False
1        False     False   False       False  False
2        False     False   False       False  False
3        False     False   False       False  False
4        False     False   False       False  False
5        False     False   False       False  False
6        False     False   False       False  False
7        False     False   False       False  False
8        False     False   False       False  False
9        False     False   False       False  False
10       False     False   False       False  False
11       False     False   False       False  False
12       False     False   False       False  False
13       False     False   False       False  False
14       False     False   False       False  False
15       False     False   False       False  False
16       False     False   False       False  False
17       False     False   False       False  False
18       False     False   False       False  False
19       False     False   False       False  False
20       False     False   False       False  False
21       False     False   False       False  False
22       False     False   False       False  False
23       False     False   False       False  False
24       False     False   False       False  False
25       False     False   False       False  False
26       False     False   False       False  False
27       False     False   False       False  False
28       False     False   False       False  False
29       False     False   False       False  False
30       False     False   False       False  False
31       False     False   False       False  False
32       False     False   False       False  False
33       False     False   False       False  False
34       False     False   False       False  False
35       False     False   False       False  False
36       False     False   False       False  False
37       False     False   False       False  False
38       False     False   False       False  False
39       False     False   False       False  False
40       False     False   False       False  False
41       False     False   False       False  False
42       False     False   False       False  False
43       False     False   False       False  False
44       False     False   False       False  False
45       False     False   False       False  False
46       False     False   False       False  False
47       False     False   False       False  False
48       False     False   False       False  False
49       False     False   False       False  False

In [22]:
df.describe()

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [23]:
df[['Salary','Experience']].mean()

Salary        78344.50
Experience        7.06
dtype: float64

In [24]:
df[df['Experience'] > 6].count()

Department    30
Employee      30
Salary        30
Experience    30
City          30
dtype: int64

In [25]:
df.groupby('Department')

In [27]:
df_grouped = df.groupby('Department')

In [28]:
df_grouped.count()

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [29]:
df_grouped.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

In [30]:
df_group_city = df.groupby('City')

In [31]:
df_group_city

In [32]:
df_group_city.describe()

              Salary                                                         \
               count          mean           std      min      25%      50%
City
Austin          13.0  81216.000000  27010.770975  38571.0  54300.0  78555.0
Chicago         11.0  76869.363636  23718.116389  39692.0  59278.0  81214.0
New York        15.0  70484.133333  33208.693076  31016.0  38396.0  68044.0
San Francisco   11.0  87144.727273  24874.543739  39268.0  68731.0  91228.0

                                  Experience                                \
                    75%       max      count      mean       std  min  25%
City
Austin         104065.0  119812.0       13.0  6.000000  3.582364  1.0  3.0
Chicago         96839.0  102409.0       11.0  7.909091  3.477198  2.0  6.0
New York        95092.0  119789.0       15.0  6.800000  4.296178  1.0  3.0
San Francisco  105644.0  116807.0       11.0  7.818182  4.556713  1.0  5.0


               50%   75%   max
City
Austin         7.0   8.0  12.0
Chicago        8.0  10.5  12.0
New York       8.0  10.0  14.0
San Francisco  7.0  12.0  14.0

In [33]:
df_group_city['Salary'].mean()

City
Austin           81216.000000
Chicago          76869.363636
New York         70484.133333
San Francisco    87144.727273
Name: Salary, dtype: float64

In [34]:
df_group_city['Experience'].mean()

City
Austin           6.000000
Chicago          7.909091
New York         6.800000
San Francisco    7.818182
Name: Experience, dtype: float64